version: 2
updates:
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    groups:
      # This is the name of your group, it will be used in PR titles and branch names
      actions-deps:
        # A pattern can be...
        patterns:
          - "*"
  - package-ecosystem: "docker"
    directory: "/docker"
    schedule:
      interval: "weekly"
    groups:
      # This is the name of your group, it will be used in PR titles and branch names
      docker-deps:
        # A pattern can be...
        patterns:
          - "*"
