version: 2
updates:
  - package-ecosystem: "docker" # See documentation for possible values
    directory: "/docker" # Location of package manifests
    schedule:
      interval: "weekly"
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
